/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 Barn_Testing.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
export function Model(props) {
	let { nodes, materials } = useGLTF(
		import.meta.env.MODE === "production"
			? "/resources/Barn_Testing.glb"
			: "/Barn_Testing.glb"
	);
	// change the color of the selected wall
	return (
		<group {...props} dispose={null}>
			<group scale={[0.008, 0.011, 0.01]}>
				<mesh
					geometry={nodes.Mesh.geometry}
					material={materials.Siding_LPSmartPanelSiding}
				/>
				<mesh
					geometry={nodes.Mesh_1.geometry}
					material={materials.Siding_BoardandBatten}
				/>
				<mesh
					geometry={nodes.Mesh_2.geometry}
					material={materials.Roofing_Shingles_DesertTan}
				/>
				<mesh
					geometry={nodes.Mesh_3.geometry}
					material={materials.Wood_Trim_Interior}
				/>
				<mesh
					geometry={nodes.Mesh_4.geometry}
					material={materials.Wood_InteriorFloor}
				/>
				<mesh geometry={nodes.Mesh_5.geometry} material={materials.Wood_Trim} />
				<mesh
					geometry={nodes.Mesh_6.geometry}
					material={materials.Metal_Interior}
				/>
				<mesh
					geometry={nodes.Mesh_7.geometry}
					material={materials.Metal_Exterior}
				/>
			</group>
			<group scale={[0.008, 0.011, 0.01]}>
				<mesh
					geometry={nodes.Mesh001.geometry}
					material={materials.Wood_Trim_Interior}
				/>
				<mesh
					geometry={nodes.Mesh001_1.geometry}
					material={materials.Wood_Interior}
				/>
				<mesh
					geometry={nodes.Mesh001_2.geometry}
					material={materials.Wood_Trim}
				/>
				<mesh
					geometry={nodes.LoftedBarn_6Wall_10x12_None_Wall1.geometry}
					material={
						props.selectedWall === "wall1"
							? new THREE.MeshStandardMaterial({ color: "red" })
							: materials.Siding_LPSmartPanelSiding
					}
				/>
				<mesh
					geometry={nodes.LoftedBarn_6Wall_10x12_None_Wall2.geometry}
					material={
						props.selectedWall === "wall2"
							? new THREE.MeshStandardMaterial({ color: "red" })
							: materials.Siding_LPSmartPanelSiding
					}
				/>
				<mesh
					geometry={nodes.LoftedBarn_6Wall_10x12_None_Wall3.geometry}
					material={
						props.selectedWall === "wall3"
							? new THREE.MeshStandardMaterial({ color: "red" })
							: materials.Siding_LPSmartPanelSiding
					}
				/>
				<mesh
					geometry={nodes.LoftedBarn_6Wall_10x12_None_Wall4.geometry}
					material={
						props.selectedWall === "wall4"
							? new THREE.MeshStandardMaterial({ color: "red" })
							: materials.Siding_LPSmartPanelSiding
					}
				/>
			</group>
		</group>
	);
}

useGLTF.preload(
	import.meta.env.MODE === "production"
		? "/resources/Barn_Testing.glb"
		: "/Barn_Testing.glb"
);
